### ISSUE TITLE
Please share spec. version of CartoType special for your GLUWP fork...

### ISSUE THREAD

**Issue by mediaexplorer74** [CartoType/CartoType-Public-8-0#1]
Hi,
I tried to "assemble" your GLUWP fork (solution). The result: false. 
The SampleApp.csproj contains the lines:
`
<Reference Include="CartoType, Version=255.255.255.255, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\Users\graham\CartoType\src\main\single_library\uwp\CartoType\x64\Release\CartoType\CartoType.winmd</HintPath>
    </Reference>
`
  Please share your "uwp-compatible" version of CartoType library special tweaked for your GLUWP fork. I need it to research your fork compatibility with W10M...
  
  Best wishes,
  mediaexplorer

**Comment by GrahamAsher** [comment]
Sorry for the late reply. I’m travelling right now and will be back at work on 26th Oct. I’ll try to answer you fully then.

Graham

**Comment by mediaexplorer74** [comment]
> Sorry for the late reply. I’m travelling right now and will be back at work on 26th Oct. I’ll try to answer you fully then. Graham


Graham, NP.
Travalling is cool thing :)
" See you later " 
- MediaExplorer

**Comment by GrahamAsher** [comment]
I haven't forgotten about this but I'm sorry, I've just been too busy fixing other things.

**Comment by mediaexplorer74** [comment]
> I haven't forgotten about this but I'm sorry, I've just been too busy fixing other things.

NP. I found another OpenGL-UWP solution... and tried on my old sweet Lumia 950. I catchad "white screen" phantom/effect. So, W10M is too old... No DX12, and normal OpenGL support...  I decided to cancel this "GL-over-UWP game".
Sorry for disturbing you.
Cheers up,
Andy
